dongi/urls.py
from dongi.models import user
from django import forms
from django.urls import path
from . import views
app_name='dongi'
urlpatterns = [
    path('', views.index, name='index'),
    path('user/index', views.userV.index, name='user_index'),
    path('user/create', views.userV.create, name='user_create'),
    path('user/', views.userV.index, name='user_index'),
    path('user/delete/<int:id>',views.userV.delete, name='user_delete'),
    path('user/edit/<int:id>',views.userV.edit, name='user_edit')


]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dongi/', include('dongi.urls')),
]

dongi/models.py
from django.db import models
from django.utils.timezone import now



class user(models.Model):
    id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    is_deleted = models.BooleanField(default=False)
    def __str__(self):
        return self.first_name

class buy(models.Model):
    id = models.AutoField(primary_key=True)
    user_id = models.CharField(max_length=50)
    product = models.CharField(max_length=50)
    price = models.FloatField()
    date = models.DateTimeField(default=now)
    def __str__(self):
        return self.product
    def __str__(self):
        return self.price
    def __str__(self):
        return self.date
    def __str__(self):
        return self.user_id


class consumer(models.Model):
    id = models.AutoField(primary_key=True)
    User_id = models.CharField(("consumer"),max_length=50)
    buy_id = models.CharField(max_length=50)

dongi/forms.py
from django import forms
from django.db.models import fields
from django.forms import ModelForm
from dongi.models import user   

class userf (ModelForm):
    class Meta:
        model = user
        fields = ["id","first_name","last_name"]
        lables = {'first_name':"First name",'last_name':"Last name"}

dongi/views.py
from django import template
from dongi.models import user
from django.http import HttpResponse
from django.template import context, loader
from .models import user
from django.shortcuts import render
from dongi.forms import userf

# def add(request):
#   if request.method == 'POST':
#      form = AllocationPlanForm(request.POST)
# form.save()
# return render(request, 'page.html', {
# 'form': AllocationPlanForm()
# })


def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")


class userV:
    def index(request):
        users = user.objects.order_by('id')
        template = loader.get_template('user/index.html')
        users_len = len(users)
        context = {
            'users': users,
            'users_len': users_len

        }
        return HttpResponse(template.render(context, request))

    def create(request):
        if request.method == 'POST':
            form = userf(request.POST)
            if form.is_valid():
                form.save()
                return userV.index(request)
        else:
            form = userf()
        context = {
            'form': form,

        }
        template = loader.get_template('user/form.html')
        return HttpResponse(template.render(context, request))

    def delete(request, id):
        user.objects.filter(id=id).delete()
        return userV.index(request)

    def edit(request, id):
        myuser = user.objects.get(id=id)
        if request.method == 'POST':
            form = userf(request.POST, instance=myuser)
            if form.is_valid():
                form.save()
                return userV.index(request)
        else:
            form = userf(instance=myuser)
        context = {
            'form': form
        }
        template = loader.get_template('user/form.html')
        return HttpResponse(template.render(context, request))

dongi/templates/user/create.html
<form action="{% url 'dongi:user_create' %}" method="POST">{% csrf_token %} {% for field in form %}
    <table>
        <tr>
            <!--<td>USERID<input type="text"></td> -->
            <TR>
                <td>FIRST NAME <input type="text"></td>
            </TR>
            <TR>
                <td>LAST NAME <input type="text"> </td>
            </TR>

        </tr>
        <input type="submit" value="Add this asshole" />
    </table>
    {% endfor %}
</form>

dongi/templates/user/form.html
<div class="container">
    <form method="POST">
        <fieldset>
            <legend>Form</legend>
            {% csrf_token %} {{ form.as_table }}
            <button type="submit" class="btn btn-primary">Add this asshole</button>
        </fieldset>
    </form>
</div>

dongi/templates/user/index.html
<style>
    #b_delete {
        background-color: #f44336;
        color: white;
        padding: 14px 15px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
    }
    
    #b_edit {
        background-color: #369ef4;
        color: white;
        padding: 14px 15px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
    }
    
    a:hover,
    a:active {
        background-color: gray;
    }
</style>
{% if users %}
<table>
    {% for user in users %}
    <tr>
        <td>{{user.id}}</td>
        <td>{{user.first_name}}</td>
        <td>{{user.last_name}}</td>
        <td><a id=b_delete href="{% url 'dongi:user_delete' user.id %}" onclick="return confirm('are you carzy?? to delete {{user.first_name}}??')">delete</a></td>
        <td><a id=b_edit href="{% url 'dongi:user_edit' user.id %}" onclick="return confirm('are you carzy?? to edit {{user.first_name}}??')">edit</a></td>
    </tr>
    {% endfor %}
</table>
{% else %}
<h1> {{users_len}} users found</h1>
{% endif %}
<form action="{% url 'dongi:user_create' %}">
    <input style="color:blue" type="submit" value="add user ma fa" />
</form>